#! /bin/bash
git pull origin master; git add .;git commit -m "$*";git push origin master
echo
echo "------------------------------"
echo "commit Info -----> "  $*
echo "------------------------------"
echo
